- roles/lacchain-bootnode/tasks/install-orion.yaml
- roles/lacchain-regular-node/tasks/install-orion.yaml
- roles/lacchain-validator-node/tasks/install-orion.yaml
Updated private transaction manager - Orion
> updated orion 1.0.0 -> 1.3.2

- README.md
Detailed Steps to install Oracle Java 11
> updated steps to install java-11

- README.md
Added text which explains the ansible scripts are not only compatible with ubuntu but also with centos7.
> Clarification in readme

- README.md
- inventory.example
> updated besu version to 1.3.5 for deployments and updates

- roles/lacchain-bootnode/tasks/install-orion.yaml
- roles/lacchain-bootnode/tasks/install-pantheon.yaml
- roles/lacchain-bootnode/tasks/update-besu.yaml
- roles/lacchain-bootnode/tasks/update-orion.yaml
- roles/lacchain-regular-node/tasks/install-orion.yaml
- roles/lacchain-regular-node/tasks/install-pantheon.yaml
- roles/lacchain-regular-node/tasks/ubuntu-dependencies.yml
- roles/lacchain-regular-node/tasks/update-besu.yaml
- roles/lacchain-regular-node/tasks/update-orion.yaml
- roles/lacchain-validator-node/tasks/install-orion.yaml
- roles/lacchain-validator-node/tasks/install-pantheon.yaml
- roles/lacchain-validator-node/tasks/update-besu.yaml
- roles/lacchain-validator-node/tasks/update-orion.yaml
Install Gradle to compile Pantheon.
> install gradle on ubuntu

- roles/lacchain-bootnode/tasks/install-pantheon.yaml
- roles/lacchain-bootnode/tasks/ubuntu-install-leveldb.yaml
- roles/lacchain-bootnode/tasks/ubuntu-install-libsodium.yaml
- roles/lacchain-bootnode/tasks/update-besu.yaml
- roles/lacchain-bootnode/tasks/update-orion.yaml
- roles/lacchain-regular-node/tasks/install-pantheon.yaml
- roles/lacchain-regular-node/tasks/ubuntu-install-leveldb.yaml
- roles/lacchain-regular-node/tasks/ubuntu-install-libsodium.yaml
- roles/lacchain-regular-node/tasks/update-besu.yaml
- roles/lacchain-regular-node/tasks/update-orion.yaml
- roles/lacchain-validator-node/tasks/install-pantheon.yaml
- roles/lacchain-validator-node/tasks/ubuntu-install-leveldb.yaml
- roles/lacchain-validator-node/tasks/ubuntu-install-libsodium.yaml
- roles/lacchain-validator-node/tasks/update-besu.yaml
- roles/lacchain-validator-node/tasks/update-orion.yaml
force shell execution in ubuntu
> execute shell in ubuntu

- README.md
- docs/files/NGINX_MANUAL_INSTALLATION.md
- docs/files/SELFSIGNED_CERTIFICATE.md
- roles/lacchain-regular-node/files/nginx.conf
- roles/lacchain-regular-node/files/nginx.repo
- roles/lacchain-regular-node/tasks/configure-nginx.yml
- roles/lacchain-regular-node/tasks/install-nginx-rhel.yml
- roles/lacchain-regular-node/tasks/install-nginx-ubuntu.yml
- roles/lacchain-regular-node/tasks/install.yaml
- roles/lacchain-regular-node/tasks/prepare-nginx.yml
- roles/lacchain-regular-node/templates/ssl.conf.j2
This pull provides the capabilities to install nginx when a new node is deployed(tls certificates should be created manually, whole instructions for this are specified in the README)
For users who installed Besu and Orion prior to this commit; please refer to README in order to follow instructions for manually installing and configuring nginx.
> Secure rpc connection

- inventory.example
- roles/lacchain-regular-node/files/orion.service
- roles/lacchain-regular-node/files/pantheon.service
- roles/lacchain-regular-node/tasks/init-orion.yaml
- roles/lacchain-regular-node/tasks/init-tuning.yaml
- roles/lacchain-regular-node/tasks/install.yaml
- roles/lacchain-regular-node/templates/openssl.j2
- roles/lacchain-regular-node/templates/orion.j2
TLS communication between orions and set memory values for orion and besu
> tls communicaction and memory setting

- README.md
- inventory.example
- roles/lacchain-bootnode/tasks/update-besu.yaml
- roles/lacchain-regular-node/tasks/update-besu.yaml
- roles/lacchain-validator-node/tasks/update-besu.yaml
Pulled Besu binaries instead of source code
> updated besu to use binaries instead of building

- roles/lacchain-regular-node/tasks/init-orion-certificate.yaml
- roles/lacchain-regular-node/tasks/init-orion.yaml
- roles/lacchain-regular-node/tasks/ubuntu-dependencies.yml
- roles/lacchain-regular-node/tasks/update.yaml
add configuration certificates and CA in update files
> tls in update configuration

- roles/lacchain-bootnode/tasks/start-ethstats-client.yaml
- roles/lacchain-regular-node/tasks/start-ethstats-client.yaml
- roles/lacchain-validator-node/tasks/start-ethstats-client.yaml
Send information of blocks to new Ethstats Server
> update ip of ethstats server

- roles/lacchain-writer-node/files/nginx-rhel.conf
> changed user on nginx nobody ==> nginx

- inventory.example
> update besu version

- DEPLOY_NODE.md
Instructions to edit network/chain ID, in order to change between mainnet, david19net and testnet
> Network ID

- roles/lacchain-bootnode/templates/pantheon-config.j2
- roles/lacchain-validator-node/templates/pantheon-config.j2
- roles/lacchain-writer-node/templates/pantheon-config.j2
prometheus gateway is added to get metrics
> add prometheus metrics

- DEPLOY_NODE.md
- roles/lacchain-writer-node/tasks/init-orion.yaml
- roles/lacchain-writer-node/tasks/update.yaml
- roles/lacchain-writer-node/templates/pantheon-config.j2
Node run besu and besu is stopped by default
> stop orion when node is installed

- DEPLOY_NODE.md
- roles/lacchain-writer-node/files/pantheon.service
> increases pantheon memory requirements to a minimum requirement 

- DEPLOY_NODE.md
New names assigned to networks
> Asign new names to networks

- roles/lacchain-writer-node/templates/startpantheon.j2
remove permissioned by files. Now is supported by smart contract
> delete permissioned by file

- roles/lacchain-bootnode/tasks/update-besu.yaml
- roles/lacchain-validator-node/tasks/update-besu.yaml
- roles/lacchain-writer-node/tasks/update-besu.yaml
> update urls to install besu

- roles/lacchain-writer-node/tasks/install-nginx-ubuntu.yml
- roles/lacchain-writer-node/templates/pantheon-config.j2
- roles/lacchain-writer-node/templates/relay-signer-config.j2
install nginx-common as dependency of nginx-full
> install nginx common

- README.md
update github branch to deploy a node on david19 network
> update url github

- roles/lacchain-validator-node/tasks/install-rotation-validator.yaml
verify is rotation validator exists before to update a Validator
> not install rotation validator if it exists

- roles/lacchain-bootnode/files/genesis.json
- roles/lacchain-validator-node/files/genesis.json
- roles/lacchain-writer-node/files/genesis.json
- roles/lacchain-writer-node/tasks/update-besu.yaml
Upgrade Ethereum version to Berlin
> upgrade Eth version to berlin

- roles/lacchain-writer-node/tasks/init-pantheon.yaml
- roles/lacchain-writer-node/tasks/install.yaml
- roles/lacchain-writer-node/tasks/main.yml
set bool parameter to force conditionals
> fix problem with python3 version
